export const compagnons = [
  {
    id: 'miaou',
    nom: 'Miaou',
    espece: 'Chat',
    emoji: '🐱',
    spriteKey: 'miaou',
    passif: '+10% esquive',
    actif: { nom: 'Griffes rapides', dmg: 2, cout: 0 },
    debloquePar: 'debut',
    affinite: 0,
    dialogues: [
      'Miaou ! On y va ?',
      'Je veille sur toi, promis.',
      'Tu sens les croquettes ?',
      'Prête pour l\'aventure ?',
      'Attention, je griffe !',
    ],
  },
  {
    id: 'hulotte',
    nom: 'Hulotte',
    espece: 'Chouette',
    emoji: '🦉',
    spriteKey: 'hulotte',
    passif: '+1 question à l\'étude',
    actif: { nom: 'Œil perçant', dmg: 0, cout: 0, effet: 'revele' },
    debloquePar: 'boss-monde-3',
    affinite: 0,
    dialogues: [
      'Hou hou ! Je vois tout.',
      'La sagesse précède la victoire.',
      'Plus de questions, plus d\'étoiles !',
      'Ma vue perce la nuit.',
    ],
  },
  {
    id: 'braise',
    nom: 'Braise',
    espece: 'Dragonnet',
    emoji: '🐲',
    spriteKey: 'braise',
    passif: '+1 dégât auto par tour',
    actif: { nom: 'Souffle ardent', dmg: 4, cout: 0 },
    debloquePar: 'boss-monde-5',
    affinite: 0,
    dialogues: [
      'Grrr ! Brûlons tout !',
      'Je crache des flammes !',
      'Chaude ambiance.',
    ],
  },
  {
    id: 'lili',
    nom: 'Lili',
    espece: 'Fée',
    emoji: '🧚',
    spriteKey: 'lili',
    passif: '+1 PV début combat, soins +1',
    actif: { nom: 'Poussière de vie', dmg: 0, cout: 0, effet: 'soin5' },
    debloquePar: 'boss-monde-7',
    affinite: 0,
    dialogues: [
      'Scintillement ! ✨',
      'Une pincée de magie pour toi.',
      'Je soigne avec les fleurs.',
    ],
  },
  {
    id: 'astra',
    nom: 'Astra',
    espece: 'Licorne',
    emoji: '🦄',
    spriteKey: 'astra',
    passif: '+1 dégât aux sorts, charges gratuites au début',
    actif: { nom: 'Arc-en-ciel', dmg: 5, cout: 0, effet: 'recharge' },
    debloquePar: 'boutique-ou-boss-monde-9',
    affinite: 0,
    dialogues: [
      'Galop mystique...',
      'L\'arc-en-ciel nous porte.',
      'Je suis ta licorne.',
    ],
  },
  {
    id: 'croquette',
    nom: 'Croquette',
    espece: 'Hérisson',
    emoji: '🦔',
    spriteKey: 'croquette',
    passif: '+1 pièce d\'or par bonne réponse',
    actif: { nom: 'Boule piquante', dmg: 3, cout: 0 },
    debloquePar: 'boss-monde-2',
    affinite: 0,
    dialogues: [
      'Pic pic ! On y va !',
      'Mes piquants protègent.',
      'Petit mais courageux.',
    ],
  },
  {
    id: 'pixel',
    nom: 'Pixel',
    espece: 'Lutin',
    emoji: '🧝',
    spriteKey: 'pixel',
    passif: '+10 % d\'esquive supplémentaire',
    actif: { nom: 'Pas de l\'ombre', dmg: 2, cout: 0, effet: 'esquive' },
    debloquePar: 'boss-monde-4',
    affinite: 0,
    dialogues: [
      'Trop rapide pour vous !',
      'Ils ne me verront pas venir.',
      'Hop hop hop, je danse.',
    ],
  },
  {
    id: 'saphir',
    nom: 'Saphir',
    espece: 'Renard de feu',
    emoji: '🦊',
    spriteKey: 'saphir',
    passif: '+1 dégât aux sorts feu et foudre',
    actif: { nom: 'Morsure ardente', dmg: 4, cout: 0 },
    debloquePar: 'boss-monde-6',
    affinite: 0,
    dialogues: [
      'Mon flair ne me trompe jamais.',
      'Je flambe l\'ennemi.',
      'Suis-moi, on va briller.',
    ],
  },
  {
    id: 'eclipse',
    nom: 'Eclipse',
    espece: 'Dragonnet noir',
    emoji: '🐉',
    spriteKey: 'eclipse',
    passif: 'Réduit de 1 les dégâts subis tous les 2 tours',
    actif: { nom: 'Aile d\'ombre', dmg: 5, cout: 0 },
    debloquePar: 'boss-monde-8',
    affinite: 0,
    dialogues: [
      'L\'ombre est ma demeure.',
      'Je veille même la nuit.',
      'Grrr... un défi !',
    ],
  },
  {
    id: 'stella',
    nom: 'Stella',
    espece: 'Esprit étoilé',
    emoji: '🌟',
    spriteKey: 'stella',
    passif: '+2 charges feu au début de chaque combat',
    actif: { nom: 'Pluie d\'étoiles', dmg: 6, cout: 0 },
    debloquePar: 'boutique-ou-boss-monde-11',
    affinite: 0,
    dialogues: [
      'Les étoiles guident notre voie.',
      'Une constellation s\'éveille.',
      'Brille avec moi !',
    ],
  },
  {
    id: 'sylphe',
    nom: 'Sylphe',
    espece: 'Sprite de la forêt',
    emoji: '🍃',
    spriteKey: 'sylphe',
    passif: '+1 dégât aux sorts vent + 1 esquive bonus',
    actif: { nom: 'Tornade verte', dmg: 4, cout: 0, effet: 'esquive' },
    debloquePar: 'boss-monde-12',
    affinite: 0,
    dialogues: [
      'Le vent murmure tes secrets.',
      'Suis le souffle des feuilles.',
      'Plus rapide que l\'éclair !',
    ],
  },
  {
    id: 'phoenix',
    nom: 'Phoenix',
    espece: 'Oiseau de feu',
    emoji: '🔥',
    spriteKey: 'phoenix',
    passif: 'Renaît avec 5 PV si KO (1 fois par combat)',
    actif: { nom: 'Plumes ardentes', dmg: 7, cout: 0 },
    debloquePar: 'boss-monde-13',
    affinite: 0,
    dialogues: [
      'De mes cendres je renais.',
      'La flamme ne s\'éteint jamais.',
      'Aucun défi ne nous arrête !',
    ],
  },
];

export const getCompagnonById = (id) => compagnons.find((c) => c.id === id);
