// Banque de questions 6ème — 1er trimestre (niveau bonus).
export const sixieme = [
  { id: 'm_6_001', monde: 11, matiere: 'maths-calcul', theme: 'priorites', difficulte: '6eme',
    enonce: 'Calcule : 3 + 4 × 2', type: 'qcm', choix: ['10', '11', '14', '24'], reponse: '11',
    explication: 'Priorité de la multiplication : 4 × 2 = 8, puis 3 + 8 = 11.' },
  { id: 'm_6_002', monde: 11, matiere: 'maths-calcul', theme: 'division', difficulte: '6eme',
    enonce: 'Division euclidienne : 47 = 5 × ? + reste 2. Quel est le quotient ?',
    type: 'saisie', reponse: '9',
    explication: '47 = 5 × 9 + 2. Le quotient est 9, le reste est 2.' },
  { id: 'm_6_003', monde: 11, matiere: 'maths-geometrie', theme: 'segments', difficulte: '6eme',
    enonce: 'Une droite a combien d\'extrémités ?',
    type: 'qcm', choix: ['0', '1', '2', 'infini'], reponse: '0',
    explication: 'Une droite est infinie des deux côtés : 0 extrémité. Segment = 2, demi-droite = 1.' },
  { id: 'm_6_004', monde: 11, matiere: 'maths-geometrie', theme: 'mediatrice', difficulte: '6eme',
    enonce: 'La médiatrice d\'un segment est une droite :',
    type: 'qcm', choix: ['parallèle', 'perpendiculaire au milieu', 'oblique', 'courbe'], reponse: 'perpendiculaire au milieu',
    explication: 'La médiatrice passe par le milieu du segment et lui est perpendiculaire.' },
  { id: 'f_6_001', monde: 11, matiere: 'francais-grammaire', theme: 'types-phrases', difficulte: '6eme',
    enonce: 'Quel est le type de phrase : « Comme c\'est beau ! »',
    type: 'qcm', choix: ['déclarative', 'interrogative', 'impérative', 'exclamative'], reponse: 'exclamative',
    explication: 'Le « ! » signale une exclamation : phrase exclamative.' },
  { id: 'f_6_002', monde: 11, matiere: 'francais-grammaire', theme: 'forme', difficulte: '6eme',
    enonce: 'Mets à la forme négative : « Je mange une pomme ».',
    type: 'qcm', choix: ['Je ne mange pas de pomme.', 'Je mange pas pomme.', 'Ne je mange.', 'Pas je mange.'], reponse: 'Je ne mange pas de pomme.',
    explication: 'Négation : ne ... pas. Et « une » devient « de » dans la négation.' },

  // ─── 15 questions supplémentaires 6ème ───
  { id: 'm_6_005', monde: 11, matiere: 'maths-calcul', theme: 'priorites', difficulte: '6eme',
    enonce: 'Calcule : (5 + 3) × 2', type: 'saisie', reponse: '16',
    explication: 'Les parenthèses d\'abord : (5+3)=8, puis 8×2 = 16.' },
  { id: 'm_6_006', monde: 11, matiere: 'maths-calcul', theme: 'priorites', difficulte: '6eme',
    enonce: '20 − 5 × 3 = ?', type: 'qcm', choix: ['5', '15', '45', '60'], reponse: '5',
    explication: 'Multiplication d\'abord : 5×3=15, puis 20−15=5.' },
  { id: 'm_6_007', monde: 11, matiere: 'maths-calcul', theme: 'fractions', difficulte: '6eme',
    enonce: 'Que vaut 3/4 de 20 ?', type: 'saisie', reponse: '15',
    explication: '20 ÷ 4 = 5 (un quart), puis 5 × 3 = 15.' },
  { id: 'm_6_008', monde: 11, matiere: 'maths-calcul', theme: 'division', difficulte: '6eme',
    enonce: 'Division euclidienne de 84 par 6. Quotient = ?',
    type: 'saisie', reponse: '14',
    explication: '84 = 6 × 14 + 0. Quotient 14.' },
  { id: 'm_6_009', monde: 11, matiere: 'maths-geometrie', theme: 'segments', difficulte: '6eme',
    enonce: 'Le milieu d\'un segment [AB] est :',
    type: 'qcm', choix: ['un point à égale distance de A et B', 'l\'extrémité A', 'un côté', 'une droite'],
    reponse: 'un point à égale distance de A et B',
    explication: 'Le milieu est équidistant des deux extrémités.' },
  { id: 'm_6_010', monde: 11, matiere: 'maths-geometrie', theme: 'droites', difficulte: '6eme',
    enonce: 'Deux droites perpendiculaires forment un angle de :',
    type: 'qcm', choix: ['45°', '90°', '180°', '0°'], reponse: '90°',
    explication: 'Perpendiculaires = angle droit = 90°.' },
  { id: 'm_6_011', monde: 11, matiere: 'maths-calcul', theme: 'pourcentages', difficulte: '6eme',
    enonce: 'Calcule 15% de 200.', type: 'saisie', reponse: '30',
    explication: '10% = 20, donc 5% = 10. 15% = 20 + 10 = 30.' },
  { id: 'f_6_003', monde: 11, matiere: 'francais-grammaire', theme: 'types-phrases', difficulte: '6eme',
    enonce: 'Quel est le type : « Est-ce que tu viens ? »',
    type: 'qcm', choix: ['déclarative', 'interrogative', 'exclamative', 'injonctive'], reponse: 'interrogative',
    explication: 'Le « ? » et « est-ce que » → phrase interrogative.' },
  { id: 'f_6_004', monde: 11, matiere: 'francais-grammaire', theme: 'types-phrases', difficulte: '6eme',
    enonce: 'Quel est le type : « Ferme la porte. »',
    type: 'qcm', choix: ['déclarative', 'interrogative', 'exclamative', 'injonctive'], reponse: 'injonctive',
    explication: 'Un ordre → phrase injonctive (ou impérative).' },
  { id: 'f_6_005', monde: 11, matiere: 'francais-grammaire', theme: 'forme', difficulte: '6eme',
    enonce: '« Je ne connais personne. » est à la forme :',
    type: 'qcm', choix: ['affirmative', 'négative', 'interrogative', 'exclamative'], reponse: 'négative',
    explication: '« Ne ... personne » = négation.' },
  { id: 'f_6_006', monde: 11, matiere: 'francais-conjugaison', theme: 'imparfait', difficulte: '6eme',
    enonce: 'Conjugue « être » à l\'imparfait : Vous ____.',
    type: 'qcm', choix: ['êtes', 'étiez', 'serez', 'êtiez'], reponse: 'étiez',
    explication: 'Être à l\'imparfait : j\'étais, tu étais, il était, nous étions, vous étiez, ils étaient.' },
  { id: 'f_6_007', monde: 11, matiere: 'francais-vocabulaire', theme: 'dictionnaire', difficulte: '6eme',
    enonce: 'Dans un dictionnaire, quel mot vient en premier ?',
    type: 'qcm', choix: ['chameau', 'chat', 'chien', 'cheval'], reponse: 'chameau',
    explication: 'Ordre : cham... < chat < chev... < chien. « Chameau » vient en premier.' },
  { id: 'f_6_008', monde: 11, matiere: 'francais-vocabulaire', theme: 'synonyme', difficulte: '6eme',
    enonce: 'Synonyme de « quotidien » ?',
    type: 'qcm', choix: ['annuel', 'mensuel', 'journalier', 'secret'], reponse: 'journalier',
    explication: '« Quotidien » = journalier (chaque jour).' },
];
