// Banque de questions CM2 (mondes 6-10).
export const cm2 = [
  // Maths CM2
  { id: 'm_c2_001', monde: 6, matiere: 'maths-calcul', theme: 'fractions', difficulte: 'CM2',
    enonce: 'Quelle fraction est la plus grande ?',
    type: 'qcm', choix: ['3/8', '1/2', '1/4', '2/8'], reponse: '1/2',
    explication: '1/2 = 4/8, plus grand que 3/8.' },
  { id: 'm_c2_002', monde: 6, matiere: 'maths-calcul', theme: 'fractions', difficulte: 'CM2',
    enonce: '2/5 + 1/5 = ?', type: 'qcm', choix: ['3/10', '3/5', '2/25', '1/5'], reponse: '3/5',
    explication: 'Même dénominateur : on additionne les numérateurs. 2 + 1 = 3 → 3/5.' },
  { id: 'm_c2_003', monde: 6, matiere: 'maths-calcul', theme: 'decimaux', difficulte: 'CM2',
    enonce: '2,5 × 10 = ?', type: 'saisie', reponse: '25',
    explication: 'Multiplier par 10 déplace la virgule d\'un cran à droite : 2,5 → 25.' },
  { id: 'm_c2_004', monde: 6, matiere: 'maths-calcul', theme: 'decimaux', difficulte: 'CM2',
    enonce: '14,7 ÷ 10 = ?', type: 'saisie', reponse: '1,47',
    explication: 'Diviser par 10 déplace la virgule d\'un cran à gauche.' },
  { id: 'm_c2_005', monde: 6, matiere: 'maths-calcul', theme: 'pourcentages', difficulte: 'CM2',
    enonce: 'Combien font 50% de 80 ?', type: 'qcm', choix: ['20', '30', '40', '50'], reponse: '40',
    explication: '50% = la moitié. 80 ÷ 2 = 40.' },
  { id: 'm_c2_006', monde: 6, matiere: 'maths-calcul', theme: 'pourcentages', difficulte: 'CM2',
    enonce: '10% de 250 = ?', type: 'saisie', reponse: '25',
    explication: '10% = diviser par 10 : 250 ÷ 10 = 25.' },
  { id: 'm_c2_007', monde: 8, matiere: 'maths-geometrie', theme: 'aire', difficulte: 'CM2',
    enonce: 'Aire d\'un rectangle 8 cm × 5 cm ?', type: 'saisie', reponse: '40',
    explication: 'A = L × l = 8 × 5 = 40 cm².' },
  { id: 'm_c2_008', monde: 8, matiere: 'maths-geometrie', theme: 'aire', difficulte: 'CM2',
    enonce: 'Aire d\'un carré de côté 6 cm ?',
    type: 'qcm', choix: ['12 cm²', '24 cm²', '36 cm²', '60 cm²'], reponse: '36 cm²',
    explication: 'A = côté × côté = 6 × 6 = 36 cm².' },

  // Français CM2
  { id: 'f_c2_001', monde: 7, matiere: 'francais-grammaire', theme: 'cod-coi', difficulte: 'CM2',
    enonce: 'Dans « Julie mange une pomme », quel est le COD ?',
    type: 'qcm', choix: ['Julie', 'mange', 'une pomme', 'aucun'], reponse: 'une pomme',
    explication: 'COD = complément d\'objet direct. On demande « quoi ? » : mange quoi ? une pomme.' },
  { id: 'f_c2_002', monde: 5, matiere: 'francais-conjugaison', theme: 'passe-compose', difficulte: 'CM2',
    enonce: 'Conjugue « manger » au passé composé : Elle ____ une pomme.',
    type: 'qcm', choix: ['mange', 'mangeait', 'a mangé', 'mangera'], reponse: 'a mangé',
    explication: 'Passé composé = auxiliaire avoir/être au présent + participe passé.' },
  { id: 'f_c2_003', monde: 5, matiere: 'francais-conjugaison', theme: 'plus-que-parfait', difficulte: 'CM2',
    enonce: 'Conjugue « finir » au plus-que-parfait : J\'____ mon travail.',
    type: 'qcm', choix: ['ai fini', 'avais fini', 'aurai fini', 'finissais'], reponse: 'avais fini',
    explication: 'Plus-que-parfait = auxiliaire à l\'imparfait + participe passé.' },
  { id: 'f_c2_004', monde: 9, matiere: 'francais-orthographe', theme: 'accord-pp', difficulte: 'CM2',
    enonce: 'Complète : « Les fleurs que j\'ai ____ sont belles. »',
    type: 'qcm', choix: ['cueilli', 'cueillie', 'cueillis', 'cueillies'], reponse: 'cueillies',
    explication: 'COD « les fleurs » placé avant : accord au féminin pluriel → cueillies.' },
  { id: 'f_c2_005', monde: 9, matiere: 'francais-orthographe', theme: 'homophone', difficulte: 'CM2',
    enonce: 'Complète : « ____ cahiers sont à moi. »',
    type: 'qcm', choix: ['Ses', 'Ces', 'C\'est', 'S\'est'], reponse: 'Ces',
    explication: '« Ces » = ceux-là. « Ses » = les siens. Ici on montre : « ces cahiers-là ».' },

  // Boss final M10 mixte
  { id: 'mix_c2_001', monde: 10, matiere: 'maths-calcul', theme: 'probleme', difficulte: 'CM2',
    enonce: 'Un livre coûte 12 €. Si on achète 4 livres, combien paie-t-on ?',
    type: 'saisie', reponse: '48',
    explication: '4 × 12 = 48 €.' },
  { id: 'mix_c2_002', monde: 10, matiere: 'francais-grammaire', theme: 'nature', difficulte: 'CM2',
    enonce: 'Quelle est la nature du mot « rapidement » ?',
    type: 'qcm', choix: ['nom', 'adjectif', 'verbe', 'adverbe'], reponse: 'adverbe',
    explication: 'Les mots en -ment sont souvent des adverbes. Ils modifient un verbe.' },

  // ─── 30 questions supplémentaires CM2 Maths ───
  { id: 'm_c2_009', monde: 6, matiere: 'maths-calcul', theme: 'fractions', difficulte: 'CM2',
    enonce: 'Combien font 3/4 + 1/4 ?', type: 'qcm', choix: ['1/4', '2/4', '4/8', '1'], reponse: '1',
    explication: '3/4 + 1/4 = 4/4 = 1 (un entier).' },
  { id: 'm_c2_010', monde: 6, matiere: 'maths-calcul', theme: 'fractions', difficulte: 'CM2',
    enonce: 'Quelle fraction est équivalente à 1/2 ?',
    type: 'qcm', choix: ['2/3', '3/5', '4/8', '5/11'], reponse: '4/8',
    explication: '4/8 = 1/2 (divise haut et bas par 4).' },
  { id: 'm_c2_011', monde: 6, matiere: 'maths-calcul', theme: 'decimaux', difficulte: 'CM2',
    enonce: '3,45 + 2,8 = ?', type: 'saisie', reponse: '6,25',
    explication: 'Aligne les virgules : 3,45 + 2,80 = 6,25.' },
  { id: 'm_c2_012', monde: 6, matiere: 'maths-calcul', theme: 'decimaux', difficulte: 'CM2',
    enonce: '15,6 − 4,8 = ?', type: 'saisie', reponse: '10,8',
    explication: '15,6 − 4,8 = 10,8.' },
  { id: 'm_c2_013', monde: 6, matiere: 'maths-calcul', theme: 'decimaux', difficulte: 'CM2',
    enonce: 'Combien vaut le chiffre des dixièmes dans 2,547 ?',
    type: 'qcm', choix: ['2', '5', '4', '7'], reponse: '5',
    explication: '2,547 : 5 = dixièmes, 4 = centièmes, 7 = millièmes.' },
  { id: 'm_c2_014', monde: 6, matiere: 'maths-calcul', theme: 'pourcentages', difficulte: 'CM2',
    enonce: '25% de 40 = ?', type: 'saisie', reponse: '10',
    explication: '25% = 1/4. 40 ÷ 4 = 10.' },
  { id: 'm_c2_015', monde: 6, matiere: 'maths-calcul', theme: 'pourcentages', difficulte: 'CM2',
    enonce: 'Un pull coûte 40€ avec 10% de réduction. Combien le paie-t-on ?',
    type: 'saisie', reponse: '36',
    explication: '10% de 40 = 4. 40 − 4 = 36€.' },
  { id: 'm_c2_016', monde: 6, matiere: 'maths-calcul', theme: 'proportionnalite', difficulte: 'CM2',
    enonce: 'Si 3 stylos coûtent 6€, combien coûtent 5 stylos ?',
    type: 'saisie', reponse: '10',
    explication: '6 ÷ 3 = 2€ par stylo. 5 × 2 = 10€.' },
  { id: 'm_c2_017', monde: 8, matiere: 'maths-geometrie', theme: 'aire', difficulte: 'CM2',
    enonce: 'Aire d\'un rectangle 12 cm × 5 cm ?',
    type: 'saisie', reponse: '60', explication: 'A = L × l = 12 × 5 = 60 cm².' },
  { id: 'm_c2_018', monde: 8, matiere: 'maths-geometrie', theme: 'perimetre', difficulte: 'CM2',
    enonce: 'Périmètre d\'un rectangle de 8 m sur 3 m ?',
    type: 'saisie', reponse: '22', explication: 'P = 2×(L+l) = 2×(8+3) = 22 m.' },
  { id: 'm_c2_019', monde: 8, matiere: 'maths-geometrie', theme: 'angles', difficulte: 'CM2',
    enonce: 'Combien de degrés dans un angle plat ?',
    type: 'qcm', choix: ['90°', '180°', '270°', '360°'], reponse: '180°',
    explication: 'L\'angle plat fait 180° (demi-tour).' },
  { id: 'm_c2_020', monde: 8, matiere: 'maths-geometrie', theme: 'geometrie', difficulte: 'CM2',
    enonce: 'Un carré a combien d\'axes de symétrie ?',
    type: 'qcm', choix: ['0', '2', '4', '8'], reponse: '4',
    explication: 'Le carré a 4 axes : 2 médianes + 2 diagonales.' },
  { id: 'm_c2_021', monde: 8, matiere: 'maths-geometrie', theme: 'aire', difficulte: 'CM2',
    enonce: 'Aire d\'un carré de côté 9 cm ?',
    type: 'saisie', reponse: '81', explication: 'A = côté² = 9 × 9 = 81 cm².' },
  { id: 'm_c2_022', monde: 2, matiere: 'maths-calcul', theme: 'multiplication', difficulte: 'CM2',
    enonce: '125 × 8 = ?', type: 'saisie', reponse: '1000',
    explication: '125 × 8 = 1 000 (astuce : 1/8 = 0,125).' },
  { id: 'm_c2_023', monde: 4, matiere: 'maths-calcul', theme: 'division', difficulte: 'CM2',
    enonce: '144 ÷ 12 = ?', type: 'saisie', reponse: '12',
    explication: '144 = 12 × 12.' },
  { id: 'm_c2_024', monde: 4, matiere: 'maths-calcul', theme: 'probleme', difficulte: 'CM2',
    enonce: 'Emma lit 25 pages par jour. Combien en 7 jours ?',
    type: 'saisie', reponse: '175', explication: '25 × 7 = 175 pages.' },

  // ─── 30 questions supplémentaires CM2 Français ───
  { id: 'f_c2_006', monde: 9, matiere: 'francais-orthographe', theme: 'accord-pp', difficulte: 'CM2',
    enonce: 'Conjugue : « La lettre que j\'ai ____. »',
    type: 'qcm', choix: ['écrit', 'écrite', 'écrits', 'écrites'], reponse: 'écrite',
    explication: 'COD « la lettre » placé avant → accord féminin singulier : écrite.' },
  { id: 'f_c2_007', monde: 9, matiere: 'francais-orthographe', theme: 'homophone', difficulte: 'CM2',
    enonce: 'Complète : « ____ il peut venir ? »',
    type: 'qcm', choix: ['Quand', 'Quant', 'Qu\'en', 'Kan'], reponse: 'Quand',
    explication: '« Quand » = à quel moment (= lorsque). « Quant à » = en ce qui concerne.' },
  { id: 'f_c2_008', monde: 9, matiere: 'francais-orthographe', theme: 'accord', difficulte: 'CM2',
    enonce: 'Complète : « Les enfants ____ fatigués. »',
    type: 'qcm', choix: ['sont', 'son', 'ce', 'ces'], reponse: 'sont',
    explication: '« Sont » = verbe être pluriel (remplaçable par « étaient »).' },
  { id: 'f_c2_009', monde: 7, matiere: 'francais-grammaire', theme: 'cod-coi', difficulte: 'CM2',
    enonce: 'Dans « Paul parle à sa sœur », « à sa sœur » est :',
    type: 'qcm', choix: ['COD', 'COI', 'sujet', 'CC temps'], reponse: 'COI',
    explication: 'COI = complément d\'objet indirect (à qui ?). Parler à quelqu\'un → COI.' },
  { id: 'f_c2_010', monde: 7, matiere: 'francais-grammaire', theme: 'cc', difficulte: 'CM2',
    enonce: 'Dans « Hier, j\'ai joué », quelle est la fonction de « Hier » ?',
    type: 'qcm', choix: ['sujet', 'COD', 'CC de temps', 'CC de lieu'], reponse: 'CC de temps',
    explication: '« Hier » = quand ? → complément circonstanciel de temps.' },
  { id: 'f_c2_011', monde: 7, matiere: 'francais-grammaire', theme: 'cc', difficulte: 'CM2',
    enonce: 'Dans « Je cours dans le parc », « dans le parc » est :',
    type: 'qcm', choix: ['sujet', 'COD', 'CC de temps', 'CC de lieu'], reponse: 'CC de lieu',
    explication: '« Dans le parc » = où ? → complément circonstanciel de lieu.' },
  { id: 'f_c2_012', monde: 7, matiere: 'francais-grammaire', theme: 'phrases', difficulte: 'CM2',
    enonce: '« Le chien aboie et le chat miaule » est une phrase :',
    type: 'qcm', choix: ['simple', 'complexe', 'interrogative', 'négative'], reponse: 'complexe',
    explication: '2 verbes conjugués (aboie + miaule) = 2 propositions = phrase complexe.' },
  { id: 'f_c2_013', monde: 5, matiere: 'francais-conjugaison', theme: 'plus-que-parfait', difficulte: 'CM2',
    enonce: 'Conjugue « voir » au plus-que-parfait : Il ____.',
    type: 'qcm', choix: ['a vu', 'avait vu', 'aurait vu', 'verra'], reponse: 'avait vu',
    explication: 'Plus-que-parfait = imparfait de l\'auxiliaire + participe passé.' },
  { id: 'f_c2_014', monde: 5, matiere: 'francais-conjugaison', theme: 'passe-simple', difficulte: 'CM2',
    enonce: 'Quelle forme est au passé simple ?',
    type: 'qcm', choix: ['il mangeait', 'il mangea', 'il a mangé', 'il mangera'], reponse: 'il mangea',
    explication: 'Passé simple (1er groupe) : il mangea (-a).' },
  { id: 'f_c2_015', monde: 5, matiere: 'francais-conjugaison', theme: 'passe-simple', difficulte: 'CM2',
    enonce: 'Conjugue « finir » au passé simple : Ils ____.',
    type: 'qcm', choix: ['finirent', 'finissent', 'finiront', 'finissaient'], reponse: 'finirent',
    explication: 'Passé simple 2e groupe : ils finirent (-irent).' },
  { id: 'f_c2_016', monde: 5, matiere: 'francais-conjugaison', theme: 'futur', difficulte: 'CM2',
    enonce: 'Conjugue « faire » au futur : Nous ____.',
    type: 'qcm', choix: ['faisons', 'faisions', 'ferons', 'fîmes'], reponse: 'ferons',
    explication: 'Faire au futur : je ferai, nous ferons, ils feront.' },
  { id: 'f_c2_017', monde: 3, matiere: 'francais-vocabulaire', theme: 'sens', difficulte: 'CM2',
    enonce: 'Dans « Cette salle de classe est une vraie ménagerie », le sens est :',
    type: 'qcm', choix: ['propre', 'figuré', 'littéral', 'mystique'], reponse: 'figuré',
    explication: 'On compare la classe à un zoo → sens figuré.' },
  { id: 'f_c2_018', monde: 3, matiere: 'francais-vocabulaire', theme: 'prefixe', difficulte: 'CM2',
    enonce: 'Que signifie le préfixe « re- » dans « refaire » ?',
    type: 'qcm', choix: ['avant', 'de nouveau', 'contre', 'sans'], reponse: 'de nouveau',
    explication: '« Re- » = de nouveau / à nouveau.' },
  { id: 'f_c2_019', monde: 3, matiere: 'francais-vocabulaire', theme: 'suffixe', difficulte: 'CM2',
    enonce: 'Quel suffixe ajoute-t-on à « fruit » pour former un adjectif ?',
    type: 'qcm', choix: ['-age', '-ier', '-é', '-able'], reponse: '-é',
    explication: 'Fruit → fruité (adjectif : qui a le goût du fruit).' },
  { id: 'f_c2_020', monde: 3, matiere: 'francais-vocabulaire', theme: 'synonyme', difficulte: 'CM2',
    enonce: 'Synonyme soutenu de « faire » ?',
    type: 'qcm', choix: ['dire', 'aller', 'effectuer', 'manger'], reponse: 'effectuer',
    explication: '« Effectuer » est un synonyme plus soutenu de « faire ».' },
];
