// Catalogue de la boutique — 4 onglets richement remplis (~100 items au total).

export const catalogue = {
  // ═══════════════════════════════════════════════════════════════
  // POTIONS (25 items)
  // ═══════════════════════════════════════════════════════════════
  potions: [
    { id: 'potion_vie_petite', nom: 'Petite potion de vie', prix: 15, icon: '🧪',
      desc: 'Rend 3 PV en combat.', effet: { type: 'pv', valeur: 3 } },
    { id: 'potion_vie_grande', nom: 'Grande potion de vie', prix: 40, icon: '🧴',
      desc: 'Rend 6 PV en combat.', effet: { type: 'pv', valeur: 6 } },
    { id: 'potion_super_vie', nom: 'Super potion de vie', prix: 80, icon: '⚗️',
      desc: 'Rend 10 PV en combat.', effet: { type: 'pv', valeur: 10 } },
    { id: 'potion_supreme', nom: 'Potion suprême', prix: 150, icon: '🏺',
      desc: 'Restaure tous les PV (max).', effet: { type: 'pv-full' } },
    { id: 'parchemin_feu', nom: 'Parchemin de feu', prix: 20, icon: '📜',
      desc: '+1 charge 🔥 instantanée.', effet: { type: 'charge', element: 'feu', valeur: 1 } },
    { id: 'parchemin_orage', nom: 'Parchemin d\'orage', prix: 30, icon: '📜',
      desc: '+1 charge ⚡ instantanée.', effet: { type: 'charge', element: 'foudre', valeur: 1 } },
    { id: 'parchemin_soin', nom: 'Parchemin de soin', prix: 25, icon: '📜',
      desc: '+1 charge 💚 instantanée.', effet: { type: 'charge', element: 'soin', valeur: 1 } },
    { id: 'parchemin_bouclier', nom: 'Parchemin de bouclier', prix: 25, icon: '📜',
      desc: '+1 charge 🛡️ instantanée.', effet: { type: 'charge', element: 'bouclier', valeur: 1 } },
    { id: 'parchemin_vent', nom: 'Parchemin de vent', prix: 25, icon: '📜',
      desc: '+1 charge 🌪️ instantanée.', effet: { type: 'charge', element: 'vent', valeur: 1 } },
    { id: 'parchemin_meteore', nom: 'Parchemin de météore', prix: 70, icon: '☄️',
      desc: 'Inflige 6 dégâts immédiats.', effet: { type: 'dmg-direct', valeur: 6 } },
    { id: 'baie_courage', nom: 'Baie de courage', prix: 40, icon: '🍒',
      desc: '+1 dégât pour le prochain sort.', effet: { type: 'boost', valeur: 1 } },
    { id: 'elixir_mana', nom: 'Élixir de mana', prix: 60, icon: '💧',
      desc: 'Recharge 1 de chaque charge.', effet: { type: 'mana' } },
    { id: 'eau_benite', nom: 'Eau bénite', prix: 90, icon: '💦',
      desc: 'Inflige 5 dégâts aux morts-vivants & boss.', effet: { type: 'dmg-boss', valeur: 5 } },
    { id: 'potion_chance', nom: 'Potion de chance ×2', prix: 35, icon: '🍀',
      desc: 'Pièces ×2 au prochain combat.', effet: { type: 'chance', duree: 1 } },
    { id: 'os_chance', nom: 'Os porte-bonheur', prix: 200, icon: '🦴',
      desc: '+50 % de pièces sur les 3 prochains combats.', effet: { type: 'chance-x3' } },
    { id: 'potion_etude', nom: 'Potion d\'étude +2 Q', prix: 25, icon: '📖',
      desc: '+2 questions à la prochaine étude.', effet: { type: 'etude', valeur: 2 } },
    { id: 'tisane_savant', nom: 'Tisane du savant', prix: 35, icon: '🍵',
      desc: 'Révèle la bonne réponse 1 fois en étude.', effet: { type: 'reveal' } },
    { id: 'friandise', nom: 'Friandise compagnon', prix: 40, icon: '🍬',
      desc: '+3 affinité avec le compagnon actif.', effet: { type: 'affinite', valeur: 3 } },
    { id: 'miel_dore', nom: 'Miel doré', prix: 90, icon: '🍯',
      desc: '+1 affinité TOUS les compagnons.', effet: { type: 'affinite-tous', valeur: 1 } },
    { id: 'potion_force_x2', nom: 'Potion de force', prix: 60, icon: '💪',
      desc: 'Sorts ×2 dégâts ce combat.', effet: { type: 'boost-sorts' } },
    { id: 'encens_calme', nom: 'Encens calmant', prix: 50, icon: '🕯️',
      desc: 'Réduit dégâts ennemis de 1 ce combat.', effet: { type: 'reduc-dmg' } },
    { id: 'fleur_serenite', nom: 'Fleur de sérénité', prix: 45, icon: '🌸',
      desc: 'Heal 5 PV + résiste à 1 sort ennemi.', effet: { type: 'heal-resist', valeur: 5 } },
    { id: 'graine_vie', nom: 'Graine de vie ★', prix: 500, icon: '🌱',
      desc: '+1 PV max PERMANENT (rare).', effet: { type: 'pv-max-perma', valeur: 1 } },
    { id: 'larme_dragon', nom: 'Larme de dragon', prix: 80, icon: '💧',
      desc: 'Restaure le bouclier au début du combat.', effet: { type: 'shield-restore' } },
    { id: 'potion_velocite', nom: 'Potion de vélocité', prix: 65, icon: '⚡',
      desc: '+1 attaque par tour ce combat.', effet: { type: 'extra-attack' } },
    { id: 'cristal_xp', nom: 'Cristal d\'XP', prix: 100, icon: '🔷',
      desc: 'Donne immédiatement 50 XP.', effet: { type: 'xp', valeur: 50 } },
    { id: 'boisson_geant', nom: 'Boisson du géant', prix: 55, icon: '🥤',
      desc: '+5 PV max ce combat.', effet: { type: 'pv-max-temp', valeur: 5 } },
    { id: 'fil_arianne', nom: 'Fil d\'Ariane', prix: 30, icon: '🧶',
      desc: 'Permet de fuir sans pénalité.', effet: { type: 'flee-safe' } },
  ],

  // ═══════════════════════════════════════════════════════════════
  // SORTS (22 items)
  // ═══════════════════════════════════════════════════════════════
  sorts: [
    { id: 'glace', nom: '🧊 Sort de Glace', prix: 80, icon: '🧊',
      desc: 'Gèle l\'ennemi 1 tour. Coûte 1 🔥.' },
    { id: 'meteore', nom: '🌟 Sort Météore', prix: 150, icon: '🌟',
      desc: '6 dégâts, ignore bouclier. Coûte 2 🔥.' },
    { id: 'miroir', nom: '💫 Sort Miroir', prix: 120, icon: '💫',
      desc: 'Renvoie la prochaine attaque. Coûte 1 🛡️.' },
    { id: 'papillons', nom: '🦋 Sort Papillons', prix: 90, icon: '🦋',
      desc: 'Esquive garantie. Coûte 1 🌪️.' },
    { id: 'tornade', nom: '🌀 Sort Tornade', prix: 110, icon: '🌀',
      desc: '4 dégâts. Coûte 2 🌪️.' },
    { id: 'soin_zone', nom: '🌿 Soin de zone', prix: 100, icon: '🌿',
      desc: 'Rend 8 PV. Coûte 2 💚.' },
    { id: 'bouclier_max', nom: '🛡️ Bouclier renforcé', prix: 130, icon: '🛡️',
      desc: 'Bouclier qui dure 3 absorptions. Coûte 2 🛡️.' },
    { id: 'arcEnCiel', nom: '⭐ Arc-en-ciel', prix: 250, icon: '🌈',
      desc: '8 dégâts mystiques. Coûte 3 charges (toute couleur).' },
    { id: 'meditation', nom: '🧘 Méditation', prix: 120, icon: '🧘',
      desc: 'Convertit 1 charge en 2 charges au choix. Coûte 1 🌪️.' },
    { id: 'foudre_double', nom: '⚡⚡ Foudre double', prix: 220, icon: '⚡',
      desc: 'Inflige 7 dégâts. Coûte 2 ⚡.' },
    { id: 'soin_total', nom: '✨ Soin total', prix: 280, icon: '✨',
      desc: 'Restaure tous les PV. Coûte 4 💚.' },
    { id: 'bouclier_magique', nom: '🛡️ Bouclier magique', prix: 180, icon: '🌀',
      desc: 'Renvoie 50 % des dégâts. Coûte 2 🛡️.' },
    { id: 'brume', nom: '🌫️ Brume', prix: 60, icon: '🌫️',
      desc: '1 dégât + ennemi rate sa prochaine attaque. Coûte 1 🌪️.' },
    { id: 'lumiere_sainte', nom: '☀️ Lumière sainte', prix: 200, icon: '☀️',
      desc: '5 dégâts ignore défense. Coûte 2 💚.' },
    { id: 'terre_tremblante', nom: '🌋 Terre tremblante', prix: 140, icon: '🌋',
      desc: '4 dégâts + étourdit l\'ennemi 1 tour. Coûte 2 🛡️.' },
    { id: 'givre_eternel', nom: '❄️ Givre éternel', prix: 180, icon: '❄️',
      desc: 'Gèle l\'ennemi 2 tours. Coûte 2 🔥.' },
    { id: 'boule_psy', nom: '🧠 Boule psychique', prix: 120, icon: '🧠',
      desc: '5 dégâts mais drain 2 PV au mage. Coûte 1 ⚡.' },
    { id: 'tempete', nom: '⛈️ Tempête', prix: 160, icon: '⛈️',
      desc: '2 dégâts × 3 tours automatiques. Coûte 3 🌪️.' },
    { id: 'priere', nom: '🙏 Prière', prix: 110, icon: '🙏',
      desc: '+5 PV + bouclier 2 absorptions. Coûte 2 💚.' },
    { id: 'enchaines', nom: '⛓️ Enchaînes', prix: 200, icon: '⛓️',
      desc: 'Bloque l\'ennemi 2 tours. Coûte 2 🛡️.' },
    { id: 'doppelganger', nom: '👥 Doppelgänger', prix: 250, icon: '👥',
      desc: 'L\'ennemi attaque sa propre image. Coûte 3 ⚡.' },
    { id: 'armure_ange', nom: '👼 Armure d\'ange', prix: 300, icon: '👼',
      desc: 'Reflet 100 % pendant 1 tour. Coûte 3 🛡️.' },
  ],

  // ═══════════════════════════════════════════════════════════════
  // ÉQUIPEMENT (28 items)
  // ═══════════════════════════════════════════════════════════════
  equipement: [
    { id: 'baguette_erable', nom: 'Baguette d\'érable', prix: 50, icon: '🪄',
      desc: '+1 dégât d\'attaque de base.', slot: 'arme' },
    { id: 'baguette_chene', nom: 'Baguette de chêne', prix: 200, icon: '🪄',
      desc: '+2 dégâts d\'attaque de base.', slot: 'arme' },
    { id: 'baguette_etoile', nom: 'Baguette étoilée', prix: 350, icon: '🪄',
      desc: '+1 dégât à TOUS les sorts.', slot: 'arme' },
    { id: 'sceptre_etoile', nom: 'Sceptre étoilé', prix: 400, icon: '🪄',
      desc: '+2 dégâts à tous les sorts.', slot: 'arme' },
    { id: 'sabre_ethere', nom: 'Sabre éthéré', prix: 350, icon: '⚔️',
      desc: '+1 dmg attaque + 1 dmg foudre.', slot: 'arme' },
    { id: 'baton_orage', nom: 'Bâton d\'orage', prix: 150, icon: '⚡',
      desc: '+1 dégât aux sorts foudre.', slot: 'arme' },
    { id: 'cristal_feu', nom: 'Cristal de feu', prix: 120, icon: '🔥',
      desc: '+1 dégât aux sorts de feu.', slot: 'accessoire' },
    { id: 'amulette_soin', nom: 'Amulette de soin', prix: 100, icon: '💚',
      desc: '+1 PV à chaque sort de soin.', slot: 'accessoire' },
    { id: 'bouclier_runique', nom: 'Bouclier runique', prix: 180, icon: '🛡️',
      desc: 'Double la durée du sort Bouclier.', slot: 'accessoire' },
    { id: 'bottes_vent', nom: 'Bottes du vent', prix: 200, icon: '👢',
      desc: '+10 % esquive.', slot: 'accessoire' },
    { id: 'masque_loup_eq', nom: 'Masque de loup', prix: 90, icon: '🐺',
      desc: '+5 % esquive.', slot: 'accessoire' },
    { id: 'robe_mage', nom: 'Robe de mage', prix: 90, icon: '🥼',
      desc: '+2 PV max au début du combat.', slot: 'accessoire' },
    { id: 'cape_velours', nom: 'Cape de velours', prix: 60, icon: '🧥',
      desc: '+2 PV max au combat.', slot: 'accessoire' },
    { id: 'tunique_runique', nom: 'Tunique runique', prix: 90, icon: '👘',
      desc: '+1 PV par sort de soin.', slot: 'accessoire' },
    { id: 'armure_cristal', nom: 'Armure de cristal', prix: 130, icon: '🛡️',
      desc: '+3 PV max au combat.', slot: 'accessoire' },
    { id: 'gants_runiques', nom: 'Gants runiques', prix: 130, icon: '🧤',
      desc: '+1 dégât d\'attaque (cumule avec arme).', slot: 'accessoire' },
    { id: 'pendentif_chance', nom: 'Pendentif de chance', prix: 110, icon: '🪬',
      desc: '+5 % de pièces gagnées.', slot: 'accessoire' },
    { id: 'medaillon_sang', nom: 'Médaillon de sang', prix: 250, icon: '🔴',
      desc: '+20 % de pièces gagnées.', slot: 'accessoire' },
    { id: 'ceinture_or', nom: 'Ceinture d\'or', prix: 200, icon: '👑',
      desc: '+1 pièce par bonne réponse.', slot: 'accessoire' },
    { id: 'cape_dragon', nom: 'Cape de dragon', prix: 350, icon: '🧣',
      desc: '-1 dégât subi à chaque attaque.', slot: 'accessoire' },
    { id: 'orbe_magique', nom: 'Orbe magique', prix: 280, icon: '🔮',
      desc: '+1 charge gratuite (de chaque type).', slot: 'accessoire' },
    { id: 'casque_savant', nom: 'Casque du savant', prix: 160, icon: '⛑️',
      desc: '+2 questions par étude.', slot: 'accessoire' },
    { id: 'lunettes_savant', nom: 'Lunettes du savant', prix: 180, icon: '👓',
      desc: '+1 question par étude.', slot: 'accessoire' },
    { id: 'bottes_acier', nom: 'Bottes d\'acier', prix: 180, icon: '👢',
      desc: '-1 dégât subi à chaque attaque.', slot: 'accessoire' },
    { id: 'plume_phenix', nom: 'Plume de phénix', prix: 400, icon: '🪶',
      desc: 'Revive à 5 PV si KO (1×/combat).', slot: 'accessoire' },
    { id: 'anneau_protection', nom: 'Anneau de protection', prix: 200, icon: '💍',
      desc: 'Bouclier auto au début du combat.', slot: 'accessoire' },
    { id: 'amulette_courage', nom: 'Amulette de courage', prix: 200, icon: '🎖️',
      desc: '+2 dégâts aux sorts si <50 % PV.', slot: 'accessoire' },
    { id: 'cape_invisible', nom: 'Cape d\'invisibilité', prix: 350, icon: '🌫️',
      desc: '1 esquive auto par combat.', slot: 'accessoire' },
  ],

  // ═══════════════════════════════════════════════════════════════
  // TENUES (28 items — cosmétiques + 2 compagnons exclusifs)
  // ═══════════════════════════════════════════════════════════════
  tenues: [
    { id: 'chapeau_etoile', nom: 'Chapeau étoilé', prix: 30, icon: '🎩', desc: 'Cosmétique étoilé.' },
    { id: 'chapeau_pointu', nom: 'Chapeau pointu', prix: 70, icon: '🎩', desc: 'Cosmétique mage classique.' },
    { id: 'masque_loup', nom: 'Masque de loup', prix: 70, icon: '🐺', desc: 'Cosmétique mystérieux.' },
    { id: 'masque_dragon', nom: 'Masque de dragon', prix: 80, icon: '🐉', desc: 'Cosmétique terrifiant.' },
    { id: 'tenue_pyjama', nom: 'Pyjama magique', prix: 50, icon: '🛌', desc: 'Cosmétique douillet.' },
    { id: 'uniforme_ecole', nom: 'Uniforme d\'école', prix: 100, icon: '🎓', desc: 'Cosmétique académique.' },
    { id: 'robe_feu', nom: 'Robe du feu', prix: 60, icon: '👗', desc: 'Cosmétique flamboyante.' },
    { id: 'robe_glace', nom: 'Robe de glace', prix: 180, icon: '❄️', desc: 'Cosmétique cristalline.' },
    { id: 'robe_fee', nom: 'Robe de fée', prix: 150, icon: '🧚', desc: 'Cosmétique éthéré.' },
    { id: 'robe_dragonnet', nom: 'Robe du dragonnet', prix: 180, icon: '🐲', desc: 'Cosmétique écailleuse.' },
    { id: 'cape_nuit', nom: 'Cape de la nuit', prix: 80, icon: '🥼', desc: 'Cosmétique sombre.' },
    { id: 'cape_arcEnCiel', nom: 'Cape arc-en-ciel', prix: 250, icon: '🌈', desc: 'Cosmétique multicolore.' },
    { id: 'cape_sombre', nom: 'Cape sombre', prix: 120, icon: '🦇', desc: 'Cosmétique gothique.' },
    { id: 'ailes_anges', nom: 'Ailes d\'ange', prix: 200, icon: '👼', desc: 'Cosmétique angélique.' },
    { id: 'ailes_diable', nom: 'Ailes de diable', prix: 200, icon: '😈', desc: 'Cosmétique démoniaque.' },
    { id: 'tenue_samurai', nom: 'Tenue samouraï', prix: 220, icon: '🥋', desc: 'Cosmétique guerrière.' },
    { id: 'tenue_chevalier', nom: 'Armure chevalier', prix: 230, icon: '⚔️', desc: 'Cosmétique noble.' },
    { id: 'costume_assassin', nom: 'Costume d\'assassin', prix: 240, icon: '🥷', desc: 'Cosmétique furtif.' },
    { id: 'tenue_pirate', nom: 'Costume de pirate', prix: 90, icon: '☠️', desc: 'Cosmétique aventurier.' },
    { id: 'couronne_reine', nom: 'Couronne de reine', prix: 200, icon: '👑', desc: 'Prestige royal.' },
    { id: 'couronne_argent', nom: 'Couronne d\'argent', prix: 100, icon: '👑', desc: 'Prestige modeste.' },
    { id: 'couronne_or', nom: 'Couronne d\'or massif', prix: 350, icon: '👑', desc: 'Prestige royal supérieur.' },
    { id: 'couronne_diamant', nom: 'Couronne de diamant', prix: 500, icon: '💎', desc: 'Prestige ultime.' },
    { id: 'tenue_or', nom: 'Tenue dorée', prix: 400, icon: '✨', desc: 'Cosmétique extravagant.' },
    { id: 'skin_heros', nom: 'Skin héroïne', prix: 300, icon: '🦸', desc: 'Skin exclusif.' },
    { id: 'skin_legende', nom: 'Skin légende', prix: 600, icon: '🌟', desc: 'Skin légendaire.' },
    { id: 'astra', nom: '🦄 Astra (compagnon)', prix: 300, icon: '🦄',
      desc: 'Compagnon licorne. Aussi via boss M9.' },
    { id: 'stella', nom: '🌟 Stella (compagnon)', prix: 500, icon: '🌟',
      desc: 'Compagnon esprit étoilé. Aussi via boss M11.' },
  ],
};
